##############################################################
# KnockBackFFA
# Created by BungeeDev aka MrCookieWarrior
# Development begin on 04.04.17
# Development Finished on 04.04.17
# Development time 2Hours
# The support of the developer is unfortunately only in German
# Support on TeamSpeak ceriox.de
# Minecraft version tested on 1.8 and 1.9
##############################################################
KnockBackFFA:
    Prefix: "&8[&3KnockBackFFA&8] &f"
    AllowJoinMessage: true
    AllowQuitMessage: true
    BungeeCord: false
    LevelName: "world"
    AllowBlockBreak: false
    AllowBlockPlace: false
    MaxPlayers: 25
    AllowServerChat: true
##############################################################
Messages:
    JoinMessage: "&a%player% &eJoined the game!"
    QuitMessage: "&c%player% &4Left the game!"
##############################################################
Group-Prefix:
    Owner: "&4Owner &7| "
    Admin: "&4Admin &7| "
    SrDeveloper: "&bSrDev &7| "
    Developer: "&bDev &7| "
    SrModerator: "&cSrMod &7| "
    Moderator: "&cMod &7| "
    SrSupporter: "&3SrSupp &7| "
    Supporter: "&9Supp &7| "
    SrBuilder: "&aSrBuilder &7| "
    Builder: "&2Builder &7| "
    YouTuber: "&5"
    Premium: "&6"
    Player: "&7"
##############################################################
Title:
    Header: ""
    Footer: ""
##############################################################
Tablist:
    Header: ""
    Footer: ""
##############################################################
Scoreboard:
    Title: "test"
    ScoreTS: "&6YourServer.net"
##############################################################
MySQL:
    Username: "root"
    Password: "secret"
    Host: "localhost"
    Datenbank: "knockbackffa"
    Port: 3306
##############################################################